### ISSUE TITLE
Crash on passing variables externally

### ISSUE THREAD

**Issue by avetise** [andyhall/noa-lt#17]
When passing variables through localStorage, sessionStorage or URL get etc for worldgen worker, they all crash the system? It worked in the other version - noa example master.

**Comment by fenomas** [comment]
Hi, did you build by forking this project? This particular repo is just slides for a talk I did years ago; it's not maintained or updated to work with the current engine, so it would probably be better to build off of noa-examples.

With that said, if you have the same issue with the current engine then I'd definitely need some sample code to guess what's going wrong.

**Comment by avetise** [comment]
We finally fixed up the issue by using the main worldgen to get from url
and passing the variable through to the msg along with 'init'/'generate'
and the other stuff.
